
version: '3.8'

services:
  king-23:
    image: david-23
    build: .
    ports:
      - '7006:3007'
    environment:
      - MONGODB_URI:'mongodb://mongo:27017/medicalBillingApp'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  
